image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
  Qt5_INSTALL_DIR: 'C:\Qt\5.15.0\msvc2019_64'
  PATH: '%Qt5_INSTALL_DIR%\bin;%PATH%'

build_script:
- cmd: >-

    mkdir build

    cd build

    echo %PATH%

    cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build . --config "Release"
 
    cpack -G WIX -B package


artifacts:
- path: build\package\*.msi
  name: installer
- path: build\src\Release\*.exe
  name: executable

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/042f605f-b378-45d8-ad16-b7695b071036/Integrations/AppVeyor?ProjectSlug=flameshot&SigningPolicySlug=test-signing
  authorization:
    secure: XDDPlgSe+e8ddGjY+P0vmd7jHgsXAX6Oyunz3CRg+6QZKU1Bkvo4xzViiR6r6YXh 
